services:
  api_prod:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    depends_on:
      - libsql
  meilisearch:
    build:
      context: ./apps/search
      dockerfile: Dockerfile
    ports:
      - "7700:7700"
    env_file:
      - ./apps/search/.env
    volumes:
      - "./meili_data:/meili_data"
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    # For some reason, the default db user
    # in the container doesn't have write permissions
    user: root
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./libsql:/var/lib/sqld
