services:
  api_prod:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    depends_on:
      - libsql
  web_prod:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: production
      args:
        # Need to specify the env vars here
        PORT: 4000
        VITE_API_BASE_URL: http://localhost:3000
        VITE_MEILISEARCH_API_URL: http://localhost:7700
        VITE_MEILISEARCH_API_KEY: MASTER_KEY
    depends_on:
      - api_prod
    ports:
      - "4000:4000"
    env_file:
      - ./apps/web/.env
  meilisearch:
    image: getmeili/meilisearch:v1.3.4
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "MASTER_KEY"
    volumes:
      - "./meili_data:/meili_data"
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    # For some reason, the default db user
    # in the container doesn't have write permissions
    user: root
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./libsql:/var/lib/sqld
