services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: >
      sh -c "pnpm run --filter api drizzle:migrate && exec pnpm turbo run dev --filter=api"
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    volumes:
      - .:/app
    depends_on:
      - libsql
  drizzle_studio:
    network_mode: host
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: >
      sh -c "pnpm run --filter api drizzle:studio --host=0.0.0.0 --port 4983"
    environment:
      - DATABASE_URL=http://localhost:8080
    volumes:
      - .:/app
    depends_on:
      - libsql
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    command: pnpm turbo run dev --filter=web -- --port 4000 --host
    depends_on:
      - api
    ports:
      - "4000:4000"
    env_file:
      - ./apps/web/.env
    volumes:
      - .:/app
  meilisearch:
    build:
      context: ./apps/search
      dockerfile: Dockerfile
    ports:
      - "7700:7700"
    env_file:
      - ./apps/search/.env
    volumes:
      - "./meili_data:/meili_data"
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    # For some reason, the default db user
    # in the container doesn't have write permissions
    user: root
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_DB_PATH=/tmp/libsql
    volumes:
      - ./libsql:/var/lib/sqld
