/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as AppLayoutRouteImport } from './routes/_app-layout/route'
import { Route as AppLayoutIndexImport } from './routes/_app-layout/index'
import { Route as LayoutSignUpRouteImport } from './routes/_layout/sign-up/route'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login/route'
import { Route as AppLayoutSettingsRouteImport } from './routes/_app-layout/settings/route'

// Create/Update Routes

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRouteRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutIndexRoute = AppLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any).lazy(() =>
  import('./routes/_app-layout/index.lazy').then((d) => d.Route),
)

const LayoutSignUpRouteRoute = LayoutSignUpRouteImport.update({
  path: '/sign-up',
  getParentRoute: () => LayoutRouteRoute,
} as any).lazy(() =>
  import('./routes/_layout/sign-up/route.lazy').then((d) => d.Route),
)

const LayoutLoginRouteRoute = LayoutLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => LayoutRouteRoute,
} as any).lazy(() =>
  import('./routes/_layout/login/route.lazy').then((d) => d.Route),
)

const AppLayoutSettingsRouteRoute = AppLayoutSettingsRouteImport.update({
  path: '/settings',
  getParentRoute: () => AppLayoutRouteRoute,
} as any).lazy(() =>
  import('./routes/_app-layout/settings/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app-layout': {
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app-layout/settings': {
      preLoaderRoute: typeof AppLayoutSettingsRouteImport
      parentRoute: typeof AppLayoutRouteImport
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/sign-up': {
      preLoaderRoute: typeof LayoutSignUpRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_app-layout/': {
      preLoaderRoute: typeof AppLayoutIndexImport
      parentRoute: typeof AppLayoutRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AppLayoutRouteRoute.addChildren([
    AppLayoutSettingsRouteRoute,
    AppLayoutIndexRoute,
  ]),
  LayoutRouteRoute.addChildren([LayoutLoginRouteRoute, LayoutSignUpRouteRoute]),
])

/* prettier-ignore-end */
