# fly.toml app configuration file generated for bahar-search on 2025-01-04T20:37:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bahar-search'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "meili_data"
  destination = "/meili_data"
  initial_size = "1gb"
