# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: "Fly Deploy"
description: "Deploy a project in the monorepo to Fly.io"
inputs:
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  fly_config:
    description: "Path to the fly.toml configuration file"
    required: true
  fly_api_token:
    description: "Fly.io API token"
    required: true
  sentry_api_auth_token:
    description: "Sentry API auth token"
    required: false
  sentry_api_project:
    description: "Sentry API project"
    required: false
  sentry_org:
    description: "Sentry organization"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - shell: bash
      run: |
        flyctl deploy \
          --remote-only \
          --dockerfile ${{ inputs.dockerfile }} \
          --config ${{ inputs.fly_config }} \
          --build-arg GITHUB_SHA=${{ github.sha }} \
          --build-arg SENTRY_API_AUTH_TOKEN=${{ inputs.sentry_api_auth_token }} \
          --build-arg SENTRY_API_PROJECT=${{ inputs.sentry_api_project }} \
          --build-arg SENTRY_ORG=${{ inputs.sentry_org }}
      env:
        FLY_API_TOKEN: ${{ inputs.fly_api_token }}
