name: Deploy Meilisearch
on:
  push:
    branches:
      - main
    paths:
      - "apps/search/**"

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fly-deploy
        with:
          dockerfile: apps/search/Dockerfile
          fly_config: apps/search/fly.toml
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
