name: Update Meilisearch Indexes for All Users

# This workflow updates the settings for all indexes for all users.

on: workflow_dispatch

jobs:
  update-indexes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Meilisearch Indexes
        run: ./scripts/update-indexes.sh
        env:
          MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILISEARCH_MASTER_KEY: ${{ secrets.MEILISEARCH_MASTER_KEY }}
